### ISSUE TITLE
当前施长志所负责项目的列表

### ISSUE THREAD

**Issue by JiuMaiwxguan** [JiuMaiwxguan/-#2]
列表包括项目名称+一句话简介。

**Comment by JiuMaiwxguan** [comment]
assign to 施长志

**Comment by chazshi** [comment]
项目：
1.气象站app，网页。
2.雾化控制器app，网页。
3.光立方。
4.对联打印机。
5.风火轮。
6.工位牌。
7.微信，app控制RGB灯。
8.正点原子的探索者开发板app。
9.温湿度和空气质量app。
10.遥控窗app。
项目简介：app包括上下行数据通信，界面布局及显示设计。网页部分包括连接fog服务器，从fog云获取数据，界面布局及显示。
当前项目进展：1，2两个项目功能上已完成，界面需要优化。其他项目已完成。
相关文档：已准备好相关文档。交接时拷给交接人，并进行分类和讲解。
